version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  nodejs:
    container_name: nodejs
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env

    depends_on:
      - mongodb

volumes:
  mongodb: {}
